name: CI

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'tests/**'
      - '*.sln'
      - '.github/workflows/ci.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - 'tests/**'
      - '*.sln'
      - '.github/workflows/ci.yml'

jobs:
  build:
    name: Build (.Net SDK ${{ matrix.dotnet-version }}, ${{ matrix.operating-system }})
    runs-on: ${{ matrix.operating-system }}
    env:
      DOTNET_NOLOGO: true
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ ubuntu-latest, windows-latest, macOS-latest ]
        dotnet-version: [ '8.0' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: .Net Restore
        run: dotnet restore
      - name: .Net Build
        run: dotnet build --no-restore
      - name: .Net Test
        run: dotnet test -f net8.0 --no-build --no-restore
